# Site
title: Jordy Williams
description: Senior Software Engineer focused on backend systems, distributed systems and voice AI. Based in Melbourne, Australia.
locale: en_GB
url: https://jordyjwilliams.github.io
baseurl: ""
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

email: jordy_williams@hotmail.co.uk
github-url: jordyjwilliams
linkedin: jordyjwilliams
resume: /assets/files/JordanWilliamsCV.pdf

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
